spring:
  application:
    name: securewebapp

server:
  port: 8443 # Can be any port, usually 443 for HTTPS
  ssl:
    key-store: classpath:keys/fullchain.p12 # Contains both the intermediate CA and server certificates
    key-store-password: "$SERVER_SSL_KEY_STORE_PASSWORD" # The 'export' password used when generating the PKCS12 file
    key-store-type: PKCS12
    key-alias: localhost # Defined using -name arg while generating the certificate

    # Client Validation (TrustStore)
    trust-store: classpath:trust/truststore.p12
    trust-store-password: "$SERVER_SSL_TRUST_STORE_PASSWORD" # The 'export' password used when generating the PKCS12 file
    trust-store-type: PKCS12

    # This triggers mTLS
    client-auth: need # Options: none, want, need
