[ req ]
distinguished_name = req_distinguished_name
prompt             = no

[ req_distinguished_name ]
C  = MK
ST = Skopje
L  = Skopje
O  = UKIM
OU = FINKI
# Below is the Common Name (CN) for the client certificate, which should match the hostname of the client.
CN = localhost

[ v3_client_req ]
# We set CA:FALSE because this is an end-entity certificate, not a CA certificate.
basicConstraints       = CA:FALSE
keyUsage               = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
subjectAltName         = @alt_names
authorityKeyIdentifier = keyid:always,issuer

[ alt_names ]
DNS.1 = localhost
IP.1 = 127.0.0.1
