[ req ]
distinguished_name = req_distinguished_name
prompt             = no

[ req_distinguished_name ]
C  = MK
ST = Skopje
L  = Skopje
O  = UKIM
OU = FINKI
# Below is the Common Name (CN) for the intermediate CA certificate, which can be any name you choose.
CN = MyIntermediateCA

[ v3_intermediate_ca ]
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer
# We set CA:true because this is a CA certificate
# pathlen:0 means this intermediate CA cannot issue certificates to other CAs
basicConstraints = critical, CA:true, pathlen:0
keyUsage = critical, digitalSignature, cRLSign, keyCertSign
