[ req ]
distinguished_name = req_distinguished_name
x509_extensions    = v3_ca
prompt             = no

[ req_distinguished_name ]
C  = MK
ST = Skopje
L  = Skopje
O  = UKIM
OU = FINKI
# Below is the Common Name (CN) for the root CA certificate, which can be any name you choose.
CN = MyRootCA

[ v3_ca ]
subjectKeyIdentifier   = hash
authorityKeyIdentifier = keyid:always,issuer
basicConstraints       = critical, CA:true
keyUsage               = critical, digitalSignature, cRLSign, keyCertSign
